<a href="https://colab.research.google.com/github/ngntrgduc/learning-python/blob/master/np_where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a >= 5, a, a * 10)

array([10, 20, 30, 40,  5,  6,  7,  8,  9])

In [9]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[0, 3], [7, 6]])

array([[1, 3],
       [3, 4]])

In [15]:
b = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(b % 2 == 0, b, 0)

array([[0, 0, 2],
       [0, 2, 4],
       [0, 0, 6]])